FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore --use-current-runtime  

# copy everything else
COPY . .

# install dotnet-ef
RUN dotnet tool install --global dotnet-ef
